//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean ExtendPointer
        {
            get
            {
                return SteamVR_Actions.default_ExtendPointer;
            }
        }
        
        public virtual SteamVR_Action_Boolean ShortenPointer
        {
            get
            {
                return SteamVR_Actions.default_ShortenPointer;
            }
        }
        
        public virtual SteamVR_Action_Boolean Delete
        {
            get
            {
                return SteamVR_Actions.default_Delete;
            }
        }
        
        public virtual SteamVR_Action_Single CreateBlock
        {
            get
            {
                return SteamVR_Actions.default_CreateBlock;
            }
        }
        
        public virtual SteamVR_Action_Single MoveTrigger
        {
            get
            {
                return SteamVR_Actions.default_MoveTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveBool
        {
            get
            {
                return SteamVR_Actions.default_MoveBool;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeColor
        {
            get
            {
                return SteamVR_Actions.default_ChangeColor;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
